### ISSUE TITLE
fps games

### ISSUE THREAD

**Issue by glennmichaelmejias** [Knightro63/cannon_physics#2]
can i make fps games with this? or racing games? thanks

**Comment by Knightro63** [comment]
Hi @glennmichaelmejias,

Yes you can use this to make an FPS game as long as you do not need to bring in a large 3d file, because the trimesh and octree have some bugs as of right now. 

If you need octree I would suggest trying to convert 
https://github.com/Knightro63/three_dart/blob/main/example/lib/games/games_fps.dart

As for a racing game I do not see why you would not be able to. There are a couple of examples that use controls to move a vehicle.

All of the capabilities of this repo can be scene here https://knightro63.github.io/cannon_physics/
